name: 'Magento 2 actions'
description: 'Test Build Deploy M2 projects'
author: 'MAD IT (www.madit.fr)'
inputs: 
  php:
    description: 'version of php to use 7.1, 7.2 or 7.4'
    default: '7.1'
  process:
    description: 'Possible values: build, static-test, integration-test, unit-test, phpcs-test, deploy-staging, deploy-production, cleanup-staging, cleanup-production, security-scan-[files|modules]'
    default: 'build'
  override_settings:
    description:  'override config and scripts dirs with your own setup/config, must respect default scalfolding 1 or 0'
    default: 0
  elasticsuite:
    description: 'your src is using elasticsuite?  1 or 0'
    default: 0
  elasticsearch:
    description: 'your src is using elasticsearch?  1 or 0'
    default: 0
  extension:
    description: 'the third party module to test in app/code.  Vendor or Vendor/MyModule'
    default: ''
  standard:
    description: 'Magento2, PSR2, PSR1, PSR12 etc... see magento-coding-standard'
    default: 'Magento2'
  deployer:
    description: 'deployer-php custom configs. Possible values, no-permission-check (there will be no permission check of writable dirs)'
    default: 'default'
runs:
  using: 'docker'
  image: 'docker://mad1t/magento-actions:latest'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
