name: 'Magento 2 actions'
description: 'Test Build Deploy M2 projects'
author: 'MAD IT (www.madit.fr)'
inputs: 
  php:
    description: 'version of php to use 7.1, 7.2 or 7.4'
    default: 'auto'
  process:
    description: 'Possible values: build, static-test, integration-test, unit-test, phpcs-test, deploy-staging, deploy-production, cleanup-staging, cleanup-production, security-scan-[files|modules]'
    default: 'build'
  override_settings:
    description:  'override config and scripts dirs with your own setup/config, must respect default scalfolding 1 or 0'
    default: 0
  elasticsuite:
    description: 'your src is using elasticsuite?  1 or 0'
    default: 0
  elasticsearch:
    description: 'your src is using elasticsearch?  1 or 0'
    default: 0
  extension:
    description: 'phpcs check on a Magento module or code base. Possible values, Vendor, Vendor/MyModule or dir path using github repository scaffolding'
    default: ''
  severity:
    description: 'MEQP magento coding standard severity check'
    default: 1
  standard:
    description: 'Magento2, PSR2, PSR1, PSR12 etc... see magento-coding-standard'
    default: 'Magento2'
  deployer:
    description: 'deployer-php custom configs. Possible values, no-permission-check (there will be no permission check of writable dirs)'
    default: 'default'
  composer_version:
    description: 'force composer version. Possible values 1 or 2'
    default: 0
  magento_version:
    description: 'the magento version to install i.e 2.4.1'
    default: 0
  disable_modules:
    description: 'List of modules to be disabled during install, comma separated e.g: Magento_Sales,Magento_Config'
    default: ''
  no_push:
    description: 'do not push magento source code to github repo values 0|1'
    default: 0
  unit_test_config:
    description: 'Unit test custom config path'
    default: 'dev/tests/unit/phpunit.xml.dist'
  unit_test_subset_path:
    description: 'Run restricted unit test subset directory path'


runs:
  using: 'docker'
  image: 'docker://ghcr.io/mad-i-t/magento-actions:3.10'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
