name: 'Magento 2 actions'
description: 'Test Build Deploy M2 projects'
author: 'MAD IT (www.madit.fr)'
inputs: 
  php:
    description: 'version of php to use 7.1, 7.2, 7.3, 7.4, 8.1 or 8.2'
    default: 'auto'
  process:
    description: 'Possible values: build, static-test, integration-test, unit-test, phpcs-test, deploy-staging, deploy-production, cleanup-staging, cleanup-production, security-scan-[files|modules]'
    default: 'build'
  themes:
    description: 'specify themes to build multiple values must be comma separated e.g (Magento/blank or Magento/blank,Magento/luma)'
  langs:
    description: 'specify build languages multiple values must be comma separated e.g (fr_FR or fr_FR,nl_NL)'
  keep_releases:
    description: 'numbers of builds / releases to keep after deployment (rotation). Possible values (int) e.g: 3'
    default: 3
  override_settings:
    description:  'override config and scripts dirs with your own setup/config, must respect default scalfolding 1 or 0'
    default: 0
  elasticsuite:
    description: 'your src is using elasticsuite?  1 or 0'
    default: 0
  elasticsearch:
    description: 'your src is using elasticsearch?  1 or 0'
  opensearch:
    description: 'your src is using opensearch?  1 or 0'
  extension:
    description: 'phpcs check on a Magento module or code base. Possible values, Vendor, Vendor/MyModule or dir path using github repository scaffolding'
    default: ''
  severity:
    description: 'MEQP magento coding standard severity check'
    default: 1
  standard:
    description: 'Magento2, PSR2, PSR1, PSR12 etc... see magento-coding-standard'
    default: 'Magento2'
  deployer:
    description: 'deployer-php custom configs. Possible values, no-permission-check (there will be no permission check of writable dirs)'
    default: 'default'
  composer_version:
    description: 'force composer version. Possible values 1 or 2'
    default: 0
  magento_version:
    description: 'the magento version to install i.e 2.4.1'
    default: 0
  disable_modules:
    description: 'List of modules to be disabled during install, comma separated e.g: Magento_Sales,Magento_Config'
    default: ''
  enable:
    description: 'enables functionalities when installing magento possible values: pwa'
    default: ''
  no_push:
    description: 'do not push magento source code to github repo values 0|1'
    default: 0
  magento_only:
    description: 'apply the process on magento code only (i.e magento dir)'
    default: 0
  pwa_studio_only:
    description: 'apply the process on pwa studio code only (i.e pwa-studio dir)'
    default: 0
  testsuite:
    description: 'custom testsuite to be ran works for integration and unit testing  e.g: "Memory Usage Tests"'
  integration_filter:
    description: 'integration test filter test in class e.g: testAppReinitializationNoMemoryLeak'
  integration_class:
    description: 'path to integration class path from dev/tests/integration e.g: "./testsuite/Magento/MemoryUsageTest.php"'
  unit_test_config:
    description: 'Unit test custom config path'
    default: 'dev/tests/unit/phpunit.xml.dist'
  unit_test_subset_path:
    description: 'Run restricted unit test subset directory path'
  md_src_path:
    description: 'path to source to be mess detected'
  ruleset:
    default: 'dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml'
    description: 'Ruleset path e.g ruleset path for mess detector'
  exec_path:
    default: '.'
    description: 'path to file or directory to exec, scan, etc... (phpstan)'
  node_version:
    description: 'node version for pwa-studio and Hyvä theme builds'
    default: 15
  version:
   description: 'generic version to be compounded with other variables e.g pwa-studio-install to specify pwa version'
  apply_patches:
    description: 'apply patches in m2-hotfixes dir or in .magento.env.yaml'
    default: 0


runs:
  using: 'docker'
  image: 'docker://ghcr.io/mad-i-t/magento-actions:3.34'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
