name: publish

on: [push]

jobs:
  publish-action-docker-image:
    runs-on: ubuntu-latest
    environment: docker-image-builder

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Building magento-actions docker image
      run: |
        docker build .  --tag ghcr.io/mad-i-t/magento-actions:3.25 --tag ghcr.io/mad-i-t/magento-actions:latest
        docker push ghcr.io/mad-i-t/magento-actions:3.25
        docker push ghcr.io/mad-i-t/magento-actions:latest
